{% set version = "5.2.0" %}

package:
  name: jemalloc
  version: {{ version }}

source:
  fn: {{ version }}.tar.bz2
  url: https://github.com/jemalloc/jemalloc/releases/download/{{ version }}/jemalloc-{{ version }}.tar.bz2
  sha256: 74be9f44a60d2a99398e706baa921e4efde82bf8fd16e5c0643c375c5851e3b4

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - test -f $PREFIX/lib/libjemalloc.so.2  # [linux]
    - test -f $PREFIX/lib/libjemalloc.a
    - test -f $PREFIX/lib/libjemalloc_pic.a
    - test -f $PREFIX/lib/libjemalloc.2.dylib  # [osx]
    - test -f $PREFIX/include/jemalloc/jemalloc.h

about:
  home: http://jemalloc.net
  dev_url: https://github.com/jemalloc/jemalloc
  license: BSD 2-Clause
  license_file: COPYING
  summary: 'general purpose malloc(3) implementation'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
