{% set version = "5.1.0" %}

package:
  name: jemalloc
  version: {{ version }}

source:
  fn: {{ version }}.tar.bz2
  url: https://github.com/jemalloc/jemalloc/releases/download/{{ version }}/jemalloc-{{ version }}.tar.bz2
  sha256: 5396e61cc6103ac393136c309fae09e44d74743c86f90e266948c50f3dbb7268

build:
  number: 1001
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - test -f $PREFIX/lib/libjemalloc.so.2  # [linux]
    - test -f $PREFIX/lib/libjemalloc.a
    - test -f $PREFIX/lib/libjemalloc_pic.a
    - test -f $PREFIX/lib/libjemalloc.2.dylib  # [osx]
    - test -f $PREFIX/include/jemalloc/jemalloc.h

about:
  home: http://jemalloc.net
  dev_url: https://github.com/jemalloc/jemalloc
  license: BSD 2-Clause
  license_file: COPYING
  summary: 'general purpose malloc(3) implementation'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
