appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure}
travis:
  secure:
    BINSTAR_TOKEN: VstBlVDwUOcgiQeNeLiO8BWN9m4F0dA8vFgaUaVGsGbk1DtUcH8RuFooW2my3EuiFv/W9d2hF4N8bvZlfUHFpWhoZe1fzpMZwzFKL9VS+fwDmtbiakEwoKhBN45xVvFy/0EjDFO61bY4jdVVbdrUtiwWobVJa0GAX5JPaI2A2BXsDdvNq0yLpucrHIH5ovCgKRLC5Eyf+H62POHzUhHG11ZPSVyvqUmAeP/tFke8E0xLSUnqezP8lbTFdZPBxsXoJo6UueaXJDSQIQMGGuQkrIYxGFapOwG7H902LxFqTicdSImrZ+2XqsB+kGFzZsmSYBJWkSkZn9dhRZcHtDVj36hQKiEpvF5XZiqIU+KvSrVmIRlJN8oiJsdZGPrmtYyhCDNynkdNALHHrQ/HzGhloFNpAan4X0ix/Maxd4at37bvnWiI5rfJTa0iFm9URsU5L5aOUFEgxfrj3gxlYEtVQT44CjICPTzKqaO88Cdfsy2xygATKBkST/P7S6AJ2kW+7tUwOljjDck+qbzRPv3PArycq6+Y7MbstWmGopNCdoVj1i5nWA/ecvQvD4V4TgtocHFFdf7D5ZRYFaVyYVZYpL4D+UMDyTIzXfplCD6NhKEAtbf6h7uhrTv5QrlV+44tPcRlHhDSD5iFS03AlZt0KAIE4J6+gqj63Y3KDsIpjH4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
