appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: YsAJ3yD1H7LJo79r9b58HXeSFGR0flHr+t4tIl1mh+TCJ0rwLfR6YhCicKcDC9DuBQpAlIk2aI5JRqDXyc7QFijj5yZLlxIr5y/uZRc+2oxC1h5Bl9rtepVC7hB9w9xsyZYcLxt7xEUQa2vAfK5J6iyYnTulKManoLAMfzxmPDFb0hyi5z0AANNRBLXriZcZrtZ6luPt+uZI4NPtLw0Tqw1qQiQcU52pHlmWbEIiySVPWV1cs0YhZSTTbXTxVN1A8e8vESJjF+gKufuujScrTXhkMSCEK43MgcANPT6pfpG5c7tsT/11EVxs840VpsvIgLlZeWFaR/OKKRJP333ZxfeM1J5H1lctD5clXqth+PIyXWhhN6oHfoaANOWy+bgZ38LfOLIBYy/NirSnbVcJC6a9wQtrlf4rFxEiPQP2UjxbB/IGn5GtEPjRbc7CnqGlblJ2TeDqTurhm4715liMrcHQ41bJV29C2+NxSSYJN99lsBgeD+mo4lxLcdKThEeY5M97DKyZLNWYuKjP7q2ld6YQIpUbv/CzrFIEvPgiTyj/9TI85Zjlabxo15ZQlEebu5H5ekCT6XbeLIl4w1KZoiOOtHPIVPD3enVASk0RYFPBN72jNLVdV+eMVUy8nYB2X6qsZg1n6WGLZswkFj94lOrcKDkqyUAuwhoxK5hyNLE=}
